apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: adonis-app
  name: adonis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adonis-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: adonis-app
    spec:
      volumes:
        - name: public-images
          hostPath:
            path: /home/ubuntu/public-images
            type: DirectoryOrCreate

      containers:
        - args:
            - node
            - ./bin/server.js
          env:
            - name: APP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: APP_DOMAIN
                  name: env
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_KEY
                  name: env
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: env
            - name: DRIVE_DISK
              valueFrom:
                configMapKeyRef:
                  key: DRIVE_DISK
                  name: env
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: env
            - name: PG_HOST
              value: postgres
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: env
          image: jeremi656/adonis-app:latest
          name: adonis-app
          ports:
            - containerPort: 3333
              protocol: TCP
            - containerPort: 9229
              protocol: TCP
          volumeMounts:
            - name: public-images
              mountPath: /app/public/images
      restartPolicy: Always
