name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to k3s via kubectl
        run: |
          set -eux
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/backend-cocktail-api/k8 || exit
            git pull origin main || exit

            # Apply everything by folder
            kubectl apply -f public-images-pvc.yaml
            kubectl apply -f env-configmap.yaml
            kubectl apply -f adonis-app/
            kubectl apply -f postgres/
            kubectl apply -f jobs/
            kubectl apply -f hpa.yaml

            # Restart your API so it picks up new image/config
            kubectl rollout restart deployment/adonis-app
          EOF

