on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build & Deploy via Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/backend-cocktail-api || exit
            git pull origin main || exit
            docker-compose down || true
            docker-compose pull || true
            docker-compose up -d --build
          EOF
